### ISSUE TITLE
Implement slab level cache for remote frees 

### ISSUE THREAD

**Issue by mjp41** [microsoft/snmalloc#634]
@nwf-msr observed that we could improve the performance of remote deallocation if the producer does more work on building lists for each slab before returning to the original allocator.  This could improve producer/consumer scenarios further.

```[tasklist]
### Tasks
- [ ] Implementing statistics to estimate performance wins.
- [ ] Implement version that doesn't work with snmalloc hardening.
- [ ] Implement version with hardening as well 
```

**Comment by mjp41** [comment]
@licenser @darach are you still using snmalloc. If so do you have any benchmarks that represent your workload?  We have some ideas that would benefit your kind of workload for Tremor.

**Comment by darach** [comment]
Hi Matt,

We sure are. In tremor, and I have a project at work ( axiom now ) where I
think it's a great fit.

We'll ask the community as well

Cheers,

Darach.

**Comment by mjp41** [comment]
Awesome thanks. Any benchmarks we can run would really help us in justifying the engineering work.

**Comment by darach** [comment]
Our CI benchmarks are snmalloc based https://www.tremor.rs/benchmarks/ - relatively boring UI there.
The benchmarks we ran a year or two ago for tremor ( and mimalloc before it, and jemalloc before that ) are here:
https://github.com/tremor-rs/tremor-runtime/blob/main/bench/README.md

They have changed enough though in themselves and we rewrote the runtime and connectors so the benchmarking
code works differently so YMMV

**Comment by nwf-msr** [comment]
I've spent a while playing with various cache strategies (though nothing very sophisticated, just sort of seeing what the low-hanging fruit was like).  For the two workloads I've tried, for three interesting choices of hashes, I currently have these message counts:

| Workload       | No caching | Perfect assembly  | 4-way direct hash |
|----------------|------------|-------------------|-------------------|
| `msgpass`      | 7,205,380  | 552,781; 35 rings | 1,076,843         |
| `xmalloc-test` | 2,388,551  | 317,057; 5 rings  | 317,065           |

The hash here is inspired by https://github.com/skeeto/hash-prospector but is sort of "a third" of that:
```
  hash = slab;
  hash *= 0x7feb352d;
  hash ^= hash >> 16;
  return (hash & 3)
```

**Comment by mjp41** [comment]
This is now completed.  #677 landed in main, and the [paper](https://www.microsoft.com/en-us/research/publication/batchit-optimizing-message-passing-allocators-for-producer-consumer-workloads-an-intellectual-abstract/) appeared at ISMM'24.
