### ISSUE TITLE
New Release 0.7

### ISSUE THREAD

**Issue by mjp41** [microsoft/snmalloc#682]
Now BatchIt has landed in snmalloc, we should set up a release.  I think it would be beneficial to have a few Markdown files explaining new features in this release.

The main things I can think of in this release are

```[tasklist]
### Tasks
- [ ] Top Level description
- [ ] Improved Start up time
- [ ] BatchIt: Improving cross thread allocation and deallocation performance
- [ ] Custom meta-data.
```
